
#ifndef DEMO_ACTOR_FINITESTATEMACHINE2_H
#define DEMO_ACTOR_FINITESTATEMACHINE2_H

#include <stdbool.h>

#define ACTOR_FSM_STATE(N,X) \
	void (*X)(N *, Actor *);\
	bool (*is##X)(N *);\
	bool (*isNot##X)(N *);\
	void (*set##X)(N *);

#define ACTOR_FSM_STATE_FUNCS(N, X) \
	static void state##X(N *sm, Actor *actor);\
	inline static bool is##X(N *sm){ return sm->sm->fsmState == sm->sm->X; }\
	inline static bool isNot##X(N *sm) { return sm->sm->fsmState != sm->sm->X; }\
	inline static void set##X(N *sm) {sm->sm->fsmState = sm->sm->X;}

//Allow to define struct name
#define ACTOR_FSM_STATE_FUNCTIONS(S,X) \
	static void state##X(S *sm, Actor * actor);\
	inline static bool is##X(S *sm){ return sm->fsmState == sm->X; }\
	inline static bool isNot##X(S *sm) { return sm->fsmState != sm->X; }\
	inline static void set##X(S *sm) {sm->fsmState = sm->X;}

#define ACTOR_FSM_STATE_INIT(X) \
	sm->X = &state##X;\
	sm->is##X = &is##X;\
	sm->isNot##X = &isNot##X;\
	sm->set##X = &set##X;    \

#define ACTOR_FSM_STATE_INIT_STRUCT(S,X) \
	sm->X = &state##X;\
	sm->is##X = &is##X;\
	sm->isNot##X = &isNot##X;\
	sm->set##X = &set##X;\

#define ACTOR_FSM_DEFINE_STATE_MACHINE \
    typedef struct

#define ACTOR_FIRST_ARG_(N, ...) N

#define ACTOR_CREATE_STRUCT_IMPL_1(STRUCT_NAME, S1) ACTOR_FSM_STATE( STRUCT_NAME, S1 );
#define ACTOR_CREATE_STRUCT_IMPL_2(STRUCT_NAME, S1, ...) ACTOR_CREATE_STRUCT_IMPL_1(STRUCT_NAME, S1) ACTOR_CREATE_STRUCT_IMPL_1(STRUCT_NAME, __VA_ARGS__)
#define ACTOR_CREATE_STRUCT_IMPL_3(STRUCT_NAME, S1, ...) ACTOR_CREATE_STRUCT_IMPL_1(STRUCT_NAME, S1) ACTOR_CREATE_STRUCT_IMPL_2(STRUCT_NAME, __VA_ARGS__)
#define ACTOR_CREATE_STRUCT_IMPL_4(STRUCT_NAME, S1, ...) ACTOR_CREATE_STRUCT_IMPL_1(STRUCT_NAME, S1) ACTOR_CREATE_STRUCT_IMPL_3(STRUCT_NAME, __VA_ARGS__)
#define ACTOR_CREATE_STRUCT_IMPL_5(STRUCT_NAME, S1, ...) ACTOR_CREATE_STRUCT_IMPL_1(STRUCT_NAME, S1) ACTOR_CREATE_STRUCT_IMPL_4(STRUCT_NAME, __VA_ARGS__)
#define ACTOR_CREATE_STRUCT_IMPL_6(STRUCT_NAME, S1, ...) ACTOR_CREATE_STRUCT_IMPL_1(STRUCT_NAME, S1) ACTOR_CREATE_STRUCT_IMPL_5(STRUCT_NAME, __VA_ARGS__)
#define ACTOR_CREATE_STRUCT_IMPL_7(STRUCT_NAME, S1, ...) ACTOR_CREATE_STRUCT_IMPL_1(STRUCT_NAME, S1) ACTOR_CREATE_STRUCT_IMPL_6(STRUCT_NAME, __VA_ARGS__)
#define ACTOR_CREATE_STRUCT_IMPL_8(STRUCT_NAME, S1, ...) ACTOR_CREATE_STRUCT_IMPL_1(STRUCT_NAME, S1) ACTOR_CREATE_STRUCT_IMPL_7(STRUCT_NAME, __VA_ARGS__)
#define ACTOR_CREATE_STRUCT_IMPL_9(STRUCT_NAME, S1, ...) ACTOR_CREATE_STRUCT_IMPL_1(STRUCT_NAME, S1) ACTOR_CREATE_STRUCT_IMPL_8(STRUCT_NAME, __VA_ARGS__)
#define ACTOR_CREATE_STRUCT_IMPL_10(STRUCT_NAME, S1, ...) ACTOR_CREATE_STRUCT_IMPL_1(STRUCT_NAME, S1) ACTOR_CREATE_STRUCT_IMPL_9(STRUCT_NAME, __VA_ARGS__)
#define ACTOR_CREATE_STRUCT_IMPL_11(STRUCT_NAME, S1, ...) ACTOR_CREATE_STRUCT_IMPL_1(STRUCT_NAME, S1) ACTOR_CREATE_STRUCT_IMPL_10(STRUCT_NAME, __VA_ARGS__)
#define ACTOR_CREATE_STRUCT_IMPL_12(STRUCT_NAME, S1, ...) ACTOR_CREATE_STRUCT_IMPL_1(STRUCT_NAME, S1) ACTOR_CREATE_STRUCT_IMPL_11(STRUCT_NAME, __VA_ARGS__)
#define ACTOR_CREATE_STRUCT_IMPL_13(STRUCT_NAME, S1, ...) ACTOR_CREATE_STRUCT_IMPL_1(STRUCT_NAME, S1) ACTOR_CREATE_STRUCT_IMPL_12(STRUCT_NAME, __VA_ARGS__)
#define ACTOR_CREATE_STRUCT_IMPL_14(STRUCT_NAME, S1, ...) ACTOR_CREATE_STRUCT_IMPL_1(STRUCT_NAME, S1) ACTOR_CREATE_STRUCT_IMPL_13(STRUCT_NAME, __VA_ARGS__)
#define ACTOR_CREATE_STRUCT_IMPL_15(STRUCT_NAME, S1, ...) ACTOR_CREATE_STRUCT_IMPL_1(STRUCT_NAME, S1) ACTOR_CREATE_STRUCT_IMPL_14(STRUCT_NAME, __VA_ARGS__)
#define ACTOR_CREATE_STRUCT_IMPL_16(STRUCT_NAME, S1, ...) ACTOR_CREATE_STRUCT_IMPL_1(STRUCT_NAME, S1) ACTOR_CREATE_STRUCT_IMPL_15(STRUCT_NAME, __VA_ARGS__)

#define ACTOR_CREATE_STRUCT_IMPL(_1,_2,_3,_4,_5,_6,_7,_8,_9,_10,_11,_12,_13,_14,_15,_16,NAME,...) NAME

#define ACTOR_CREATE_FSTRUCT_IMPL_1(STRUCT_NAME, S1) ACTOR_FSM_STATE_FUNCTIONS(STRUCT_NAME, S1 );
#define ACTOR_CREATE_FSTRUCT_IMPL_2(STRUCT_NAME, S1, ...) ACTOR_CREATE_FSTRUCT_IMPL_1(STRUCT_NAME,S1) ACTOR_CREATE_FSTRUCT_IMPL_1(STRUCT_NAME,__VA_ARGS__)
#define ACTOR_CREATE_FSTRUCT_IMPL_3(STRUCT_NAME, S1, ...) ACTOR_CREATE_FSTRUCT_IMPL_1(STRUCT_NAME,S1) ACTOR_CREATE_FSTRUCT_IMPL_2(STRUCT_NAME,__VA_ARGS__)
#define ACTOR_CREATE_FSTRUCT_IMPL_4(STRUCT_NAME, S1, ...) ACTOR_CREATE_FSTRUCT_IMPL_1(STRUCT_NAME,S1) ACTOR_CREATE_FSTRUCT_IMPL_3(STRUCT_NAME,__VA_ARGS__)
#define ACTOR_CREATE_FSTRUCT_IMPL_5(STRUCT_NAME, S1, ...) ACTOR_CREATE_FSTRUCT_IMPL_1(STRUCT_NAME,S1) ACTOR_CREATE_FSTRUCT_IMPL_4(STRUCT_NAME,__VA_ARGS__)
#define ACTOR_CREATE_FSTRUCT_IMPL_6(STRUCT_NAME, S1, ...) ACTOR_CREATE_FSTRUCT_IMPL_1(STRUCT_NAME,S1) ACTOR_CREATE_FSTRUCT_IMPL_5(STRUCT_NAME,__VA_ARGS__)
#define ACTOR_CREATE_FSTRUCT_IMPL_7(STRUCT_NAME, S1, ...) ACTOR_CREATE_FSTRUCT_IMPL_1(STRUCT_NAME,S1) ACTOR_CREATE_FSTRUCT_IMPL_6(STRUCT_NAME,__VA_ARGS__)
#define ACTOR_CREATE_FSTRUCT_IMPL_8(STRUCT_NAME, S1, ...) ACTOR_CREATE_FSTRUCT_IMPL_1(STRUCT_NAME,S1) ACTOR_CREATE_FSTRUCT_IMPL_7(STRUCT_NAME,__VA_ARGS__)
#define ACTOR_CREATE_FSTRUCT_IMPL_9(STRUCT_NAME, S1, ...) ACTOR_CREATE_FSTRUCT_IMPL_1(STRUCT_NAME,S1) ACTOR_CREATE_FSTRUCT_IMPL_8(STRUCT_NAME,__VA_ARGS__)
#define ACTOR_CREATE_FSTRUCT_IMPL_10(STRUCT_NAME, S1, ...) ACTOR_CREATE_FSTRUCT_IMPL_1(STRUCT_NAME,S1) ACTOR_CREATE_FSTRUCT_IMPL_9(STRUCT_NAME,__VA_ARGS__)
#define ACTOR_CREATE_FSTRUCT_IMPL_11(STRUCT_NAME, S1, ...) ACTOR_CREATE_FSTRUCT_IMPL_1(STRUCT_NAME,S1) ACTOR_CREATE_FSTRUCT_IMPL_10(STRUCT_NAME,__VA_ARGS__)
#define ACTOR_CREATE_FSTRUCT_IMPL_12(STRUCT_NAME, S1, ...) ACTOR_CREATE_FSTRUCT_IMPL_1(STRUCT_NAME,S1) ACTOR_CREATE_FSTRUCT_IMPL_11(STRUCT_NAME,__VA_ARGS__)
#define ACTOR_CREATE_FSTRUCT_IMPL_13(STRUCT_NAME, S1, ...) ACTOR_CREATE_FSTRUCT_IMPL_1(STRUCT_NAME,S1) ACTOR_CREATE_FSTRUCT_IMPL_12(STRUCT_NAME,__VA_ARGS__)
#define ACTOR_CREATE_FSTRUCT_IMPL_14(STRUCT_NAME, S1, ...) ACTOR_CREATE_FSTRUCT_IMPL_1(STRUCT_NAME,S1) ACTOR_CREATE_FSTRUCT_IMPL_13(STRUCT_NAME,__VA_ARGS__)
#define ACTOR_CREATE_FSTRUCT_IMPL_15(STRUCT_NAME, S1, ...) ACTOR_CREATE_FSTRUCT_IMPL_1(STRUCT_NAME,S1) ACTOR_CREATE_FSTRUCT_IMPL_14(STRUCT_NAME,__VA_ARGS__)
#define ACTOR_CREATE_FSTRUCT_IMPL_16(STRUCT_NAME, S1, ...) ACTOR_CREATE_FSTRUCT_IMPL_1(STRUCT_NAME,S1) ACTOR_CREATE_FSTRUCT_IMPL_15(STRUCT_NAME,__VA_ARGS__)

#define ACTOR_CREATE_FSTRUCT_IMPL(_1,_2,_3,_4,_5,_6,_7,_8,_9,_10,_11,_12,_13,_14,_15,_16,NAME,...) NAME

#define ACTOR_CREATE_INIT_IMPL_1(STRUCT_NAME, S1) ACTOR_FSM_STATE_INIT_STRUCT(STRUCT_NAME, S1 );
#define ACTOR_CREATE_INIT_IMPL_2(STRUCT_NAME, S1, ...) ACTOR_CREATE_INIT_IMPL_1(STRUCT_NAME,S1) ACTOR_CREATE_INIT_IMPL_1(STRUCT_NAME,__VA_ARGS__)
#define ACTOR_CREATE_INIT_IMPL_3(STRUCT_NAME, S1, ...) ACTOR_CREATE_INIT_IMPL_1(STRUCT_NAME,S1) ACTOR_CREATE_INIT_IMPL_2(STRUCT_NAME,__VA_ARGS__)
#define ACTOR_CREATE_INIT_IMPL_4(STRUCT_NAME, S1, ...) ACTOR_CREATE_INIT_IMPL_1(STRUCT_NAME,S1) ACTOR_CREATE_INIT_IMPL_3(STRUCT_NAME,__VA_ARGS__)
#define ACTOR_CREATE_INIT_IMPL_5(STRUCT_NAME, S1, ...) ACTOR_CREATE_INIT_IMPL_1(STRUCT_NAME,S1) ACTOR_CREATE_INIT_IMPL_4(STRUCT_NAME,__VA_ARGS__)
#define ACTOR_CREATE_INIT_IMPL_6(STRUCT_NAME, S1, ...) ACTOR_CREATE_INIT_IMPL_1(STRUCT_NAME,S1) ACTOR_CREATE_INIT_IMPL_5(STRUCT_NAME,__VA_ARGS__)
#define ACTOR_CREATE_INIT_IMPL_7(STRUCT_NAME, S1, ...) ACTOR_CREATE_INIT_IMPL_1(STRUCT_NAME,S1) ACTOR_CREATE_INIT_IMPL_6(STRUCT_NAME,__VA_ARGS__)
#define ACTOR_CREATE_INIT_IMPL_8(STRUCT_NAME, S1, ...) ACTOR_CREATE_INIT_IMPL_1(STRUCT_NAME,S1) ACTOR_CREATE_INIT_IMPL_7(STRUCT_NAME,__VA_ARGS__)
#define ACTOR_CREATE_INIT_IMPL_9(STRUCT_NAME, S1, ...) ACTOR_CREATE_INIT_IMPL_1(STRUCT_NAME,S1) ACTOR_CREATE_INIT_IMPL_8(STRUCT_NAME,__VA_ARGS__)
#define ACTOR_CREATE_INIT_IMPL_10(STRUCT_NAME, S1, ...) ACTOR_CREATE_INIT_IMPL_1(STRUCT_NAME,S1) ACTOR_CREATE_INIT_IMPL_9(STRUCT_NAME,__VA_ARGS__)
#define ACTOR_CREATE_INIT_IMPL_11(STRUCT_NAME, S1, ...) ACTOR_CREATE_INIT_IMPL_1(STRUCT_NAME,S1) ACTOR_CREATE_INIT_IMPL_10(STRUCT_NAME,__VA_ARGS__)
#define ACTOR_CREATE_INIT_IMPL_12(STRUCT_NAME, S1, ...) ACTOR_CREATE_INIT_IMPL_1(STRUCT_NAME,S1) ACTOR_CREATE_INIT_IMPL_11(STRUCT_NAME,__VA_ARGS__)
#define ACTOR_CREATE_INIT_IMPL_13(STRUCT_NAME, S1, ...) ACTOR_CREATE_INIT_IMPL_1(STRUCT_NAME,S1) ACTOR_CREATE_INIT_IMPL_12(STRUCT_NAME,__VA_ARGS__)
#define ACTOR_CREATE_INIT_IMPL_14(STRUCT_NAME, S1, ...) ACTOR_CREATE_INIT_IMPL_1(STRUCT_NAME,S1) ACTOR_CREATE_INIT_IMPL_13(STRUCT_NAME,__VA_ARGS__)
#define ACTOR_CREATE_INIT_IMPL_15(STRUCT_NAME, S1, ...) ACTOR_CREATE_INIT_IMPL_1(STRUCT_NAME,S1) ACTOR_CREATE_INIT_IMPL_14(STRUCT_NAME,__VA_ARGS__)
#define ACTOR_CREATE_INIT_IMPL_16(STRUCT_NAME, S1, ...) ACTOR_CREATE_INIT_IMPL_1(STRUCT_NAME,S1) ACTOR_CREATE_INIT_IMPL_15(STRUCT_NAME,__VA_ARGS__)

#define ACTOR_CREATE_INIT_IMPL(_1,_2,_3,_4,_5,_6,_7,_8,_9,_10,_11,_12,_13,_14,_15,_16,NAME,...) NAME

/**
 * Name of the state machine
 * List of states
 */
#define ACTOR_CREATE_STATE_MACHINE(N, ...) \
    typedef struct N N; \
    ACTOR_FSM_DEFINE_STATE_MACHINE N {       \
    void (*fsmState)(N *, Actor *); \
    void (*update)(N *, Actor *);\
    ACTOR_CREATE_STRUCT_IMPL(__VA_ARGS__, ACTOR_CREATE_STRUCT_IMPL_16, ACTOR_CREATE_STRUCT_IMPL_15, ACTOR_CREATE_STRUCT_IMPL_14, ACTOR_CREATE_STRUCT_IMPL_13, ACTOR_CREATE_STRUCT_IMPL_12, ACTOR_CREATE_STRUCT_IMPL_11, ACTOR_CREATE_STRUCT_IMPL_10, ACTOR_CREATE_STRUCT_IMPL_9, ACTOR_CREATE_STRUCT_IMPL_8, ACTOR_CREATE_STRUCT_IMPL_7, ACTOR_CREATE_STRUCT_IMPL_6, ACTOR_CREATE_STRUCT_IMPL_5, ACTOR_CREATE_STRUCT_IMPL_4, ACTOR_CREATE_STRUCT_IMPL_3, ACTOR_CREATE_STRUCT_IMPL_2, ACTOR_CREATE_STRUCT_IMPL_1)(N,__VA_ARGS__) } N;\
    ACTOR_CREATE_FSTRUCT_IMPL(__VA_ARGS__, ACTOR_CREATE_FSTRUCT_IMPL_16, ACTOR_CREATE_FSTRUCT_IMPL_15, ACTOR_CREATE_FSTRUCT_IMPL_14, ACTOR_CREATE_FSTRUCT_IMPL_13, ACTOR_CREATE_FSTRUCT_IMPL_12, ACTOR_CREATE_FSTRUCT_IMPL_11, ACTOR_CREATE_FSTRUCT_IMPL_10, ACTOR_CREATE_FSTRUCT_IMPL_9, ACTOR_CREATE_FSTRUCT_IMPL_8, ACTOR_CREATE_FSTRUCT_IMPL_7, ACTOR_CREATE_FSTRUCT_IMPL_6, ACTOR_CREATE_FSTRUCT_IMPL_5, ACTOR_CREATE_FSTRUCT_IMPL_4, ACTOR_CREATE_FSTRUCT_IMPL_3, ACTOR_CREATE_FSTRUCT_IMPL_2, ACTOR_CREATE_FSTRUCT_IMPL_1)(N,__VA_ARGS__)           \
    inline static void update##N(N *sm, Actor *actor) { sm->fsmState(sm, actor); }                                 \
    static void init##N(N * sm) {          \
        ACTOR_CREATE_INIT_IMPL(__VA_ARGS__, ACTOR_CREATE_INIT_IMPL_16, ACTOR_CREATE_INIT_IMPL_15, ACTOR_CREATE_INIT_IMPL_14, ACTOR_CREATE_INIT_IMPL_13, ACTOR_CREATE_INIT_IMPL_12, ACTOR_CREATE_INIT_IMPL_11, ACTOR_CREATE_INIT_IMPL_10, ACTOR_CREATE_INIT_IMPL_9, ACTOR_CREATE_INIT_IMPL_8, ACTOR_CREATE_INIT_IMPL_7, ACTOR_CREATE_INIT_IMPL_6, ACTOR_CREATE_INIT_IMPL_5, ACTOR_CREATE_INIT_IMPL_4, ACTOR_CREATE_INIT_IMPL_3, ACTOR_CREATE_INIT_IMPL_2, ACTOR_CREATE_INIT_IMPL_1)(N,__VA_ARGS__) \
        sm->fsmState = sm->ACTOR_FIRST_ARG_(__VA_ARGS__);                                                                                                                      \
        sm->update = &update##N;\
    }


#endif //DEMO_FINITESTATEMACHINE_H
